# Generated by Django 3.2.6 on 2021-11-30 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211130_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plansday',
            name='shopname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.plansmonth', verbose_name='Название ТТ'),
        ),
    ]
