# Generated by Django 3.2.6 on 2021-11-30 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_plansday_shopname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plansday',
            name='persone',
        ),
        migrations.AlterField(
            model_name='plansday',
            name='shopname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.plansmonth', verbose_name='Планы ТТ'),
        ),
    ]
